"""
graph_edge_utils.py

Utility functions for adding generated ontology/KG edges to a NetworkX graph.

Expected design:
- Manual/curated edges live in edges.csv.
- Obvious foreign-key relationships are generated here from structured CSV fields.

This module assumes nodes have already been added to the graph from the entity CSV files.
It is intentionally tolerant of missing CSVs/columns because some ontology files may be empty
at the start of the project.
"""

from __future__ import annotations

from typing import Dict, Iterable, Optional

import networkx as nx
import pandas as pd


DataFrames = Dict[str, pd.DataFrame]


def _has_columns(df: pd.DataFrame, columns: Iterable[str]) -> bool:
    """Return True if every required column exists in the DataFrame."""
    return all(column in df.columns for column in columns)


def _clean(value: object) -> str:
    """Normalize missing values and whitespace to a clean string."""
    if value is None:
        return ""
    if pd.isna(value):
        return ""
    return str(value).strip()


def _split_pipe(value: object) -> list[str]:
    """Split pipe-delimited values such as 'object_detection|classification'."""
    text = _clean(value)
    if not text:
        return []
    return [part.strip() for part in text.split("|") if part.strip()]


def _node_exists(G: nx.MultiDiGraph, node_id: str) -> bool:
    return bool(node_id) and node_id in G


def _add_edge_if_nodes_exist(
    G: nx.MultiDiGraph,
    source_id: str,
    target_id: str,
    relation: str,
    *,
    generated: bool = True,
    evidence_id: str = "",
    confidence: str = "",
    notes: str = "",
) -> bool:
    """
    Add an edge only if source and target nodes already exist.

    Returns True if an edge was added, otherwise False.
    """
    source_id = _clean(source_id)
    target_id = _clean(target_id)
    if not (_node_exists(G, source_id) and _node_exists(G, target_id)):
        return False

    attrs = {
        "relation": relation,
        "generated": generated,
    }
    if evidence_id:
        attrs["evidence_id"] = evidence_id
    if confidence:
        attrs["confidence"] = confidence
    if notes:
        attrs["notes"] = notes

    G.add_edge(source_id, target_id, **attrs)
    return True


def add_training_recipe_edges(G: nx.MultiDiGraph, dfs: DataFrames) -> None:
    """
    Generate edges from training_recipes.csv.

    Generated edges:
    - TrainingRecipe --for_task--> Task, using training_recipes.task_id
    - Model --has_training_recipe--> TrainingRecipe, using models.model_family == training_recipes.model_family
    - TrainingRecipe --uses_metric--> EvaluationMetric, using optional metric_ids / primary_metric_ids / secondary_metric_ids
    """
    recipes = dfs.get("training_recipes", pd.DataFrame())
    models = dfs.get("models", pd.DataFrame())

    if recipes.empty or "id" not in recipes.columns:
        return

    for _, recipe in recipes.iterrows():
        recipe_id = _clean(recipe.get("id"))
        task_id = _clean(recipe.get("task_id"))
        model_family = _clean(recipe.get("model_family"))

        if task_id:
            _add_edge_if_nodes_exist(
                G,
                recipe_id,
                task_id,
                "for_task",
                notes="Generated from training_recipes.task_id.",
            )

        # Model -> TrainingRecipe via shared model_family.
        if model_family and not models.empty and _has_columns(models, ["id", "model_family"]):
            matching_models = models[models["model_family"].map(_clean) == model_family]
            for _, model in matching_models.iterrows():
                model_id = _clean(model.get("id"))
                _add_edge_if_nodes_exist(
                    G,
                    model_id,
                    recipe_id,
                    "has_training_recipe",
                    notes="Generated by matching models.model_family to training_recipes.model_family.",
                )

        # Optional metric fields. Add these columns later if desired.
        for metric_column in ["metric_ids", "primary_metric_ids", "secondary_metric_ids"]:
            if metric_column not in recipes.columns:
                continue
            for metric_id in _split_pipe(recipe.get(metric_column)):
                _add_edge_if_nodes_exist(
                    G,
                    recipe_id,
                    metric_id,
                    "uses_metric",
                    notes=f"Generated from training_recipes.{metric_column}.",
                )


def add_model_benchmark_result_edges(G: nx.MultiDiGraph, dfs: DataFrames) -> None:
    """
    Generate edges from model_benchmark_results.csv.

    Generated edges:
    - Model --has_benchmark_result--> ModelBenchmarkResult, using model_id
    - ModelBenchmarkResult --measures_metric--> EvaluationMetric, using metric_id
    - ModelBenchmarkResult --measured_on_hardware--> HardwareProfile, using hardware_profile_id if present
    - ModelBenchmarkResult --evaluated_for_task--> Task, using task_id
    - ModelBenchmarkResult --supported_by_evidence--> EvidenceSource, using source_id
    """
    benchmarks = dfs.get("model_benchmark_results", pd.DataFrame())
    if benchmarks.empty or "id" not in benchmarks.columns:
        return

    for _, result in benchmarks.iterrows():
        result_id = _clean(result.get("id"))
        model_id = _clean(result.get("model_id"))
        metric_id = _clean(result.get("metric_id"))
        hardware_profile_id = _clean(result.get("hardware_profile_id"))
        task_id = _clean(result.get("task_id"))
        source_id = _clean(result.get("source_id"))
        confidence = _clean(result.get("confidence"))

        _add_edge_if_nodes_exist(
            G,
            model_id,
            result_id,
            "has_benchmark_result",
            evidence_id=source_id,
            confidence=confidence,
            notes="Generated from model_benchmark_results.model_id.",
        )
        _add_edge_if_nodes_exist(
            G,
            result_id,
            metric_id,
            "measures_metric",
            evidence_id=source_id,
            confidence=confidence,
            notes="Generated from model_benchmark_results.metric_id.",
        )
        if hardware_profile_id:
            _add_edge_if_nodes_exist(
                G,
                result_id,
                hardware_profile_id,
                "measured_on_hardware",
                evidence_id=source_id,
                confidence=confidence,
                notes="Generated from model_benchmark_results.hardware_profile_id.",
            )
        _add_edge_if_nodes_exist(
            G,
            result_id,
            task_id,
            "evaluated_for_task",
            evidence_id=source_id,
            confidence=confidence,
            notes="Generated from model_benchmark_results.task_id.",
        )
        _add_edge_if_nodes_exist(
            G,
            result_id,
            source_id,
            "supported_by_evidence",
            confidence=confidence,
            notes="Generated from model_benchmark_results.source_id.",
        )


def add_evaluation_metric_edges(G: nx.MultiDiGraph, dfs: DataFrames) -> None:
    """
    Generate edges from evaluation_metrics.csv.

    Generated edges:
    - EvaluationMetric --applies_to_task--> Task, using task_id

    If task_id is 'all', this function does not create task edges by default.
    """
    metrics = dfs.get("evaluation_metrics", pd.DataFrame())
    if metrics.empty or not _has_columns(metrics, ["id", "task_id"]):
        return

    for _, metric in metrics.iterrows():
        metric_id = _clean(metric.get("id"))
        task_id = _clean(metric.get("task_id"))
        if not task_id or task_id.lower() == "all":
            continue
        _add_edge_if_nodes_exist(
            G,
            metric_id,
            task_id,
            "applies_to_task",
            notes="Generated from evaluation_metrics.task_id.",
        )


def add_adjustment_rule_edges(G: nx.MultiDiGraph, dfs: DataFrames) -> None:
    """
    Generate edges from adjustment_rules.csv.

    Generated edges:
    - AdjustmentRule --applies_to_task--> Task, using applies_to_task_ids
    - AdjustmentRule --applies_to_model--> Model, using applies_to_model_families matched to models.model_family
    - AdjustmentRule --modifies_recipe--> TrainingRecipe, using matching task_id and model_family
    """
    rules = dfs.get("adjustment_rules", pd.DataFrame())
    models = dfs.get("models", pd.DataFrame())
    recipes = dfs.get("training_recipes", pd.DataFrame())

    if rules.empty or "id" not in rules.columns:
        return

    for _, rule in rules.iterrows():
        rule_id = _clean(rule.get("id"))
        task_ids = _split_pipe(rule.get("applies_to_task_ids"))
        model_families = _split_pipe(rule.get("applies_to_model_families"))
        confidence = _clean(rule.get("confidence"))

        for task_id in task_ids:
            _add_edge_if_nodes_exist(
                G,
                rule_id,
                task_id,
                "applies_to_task",
                confidence=confidence,
                notes="Generated from adjustment_rules.applies_to_task_ids.",
            )

        # Rule -> Model via model family matching.
        if model_families and not models.empty and _has_columns(models, ["id", "model_family"]):
            for _, model in models.iterrows():
                model_id = _clean(model.get("id"))
                model_family = _clean(model.get("model_family"))
                if model_family in model_families:
                    _add_edge_if_nodes_exist(
                        G,
                        rule_id,
                        model_id,
                        "applies_to_model",
                        confidence=confidence,
                        notes="Generated by matching adjustment_rules.applies_to_model_families to models.model_family.",
                    )

        # Rule -> TrainingRecipe via shared task_id and model_family.
        if not recipes.empty and _has_columns(recipes, ["id", "task_id", "model_family"]):
            for _, recipe in recipes.iterrows():
                recipe_id = _clean(recipe.get("id"))
                recipe_task_id = _clean(recipe.get("task_id"))
                recipe_model_family = _clean(recipe.get("model_family"))

                task_matches = not task_ids or recipe_task_id in task_ids
                family_matches = not model_families or recipe_model_family in model_families

                if task_matches and family_matches:
                    _add_edge_if_nodes_exist(
                        G,
                        rule_id,
                        recipe_id,
                        "modifies_recipe",
                        confidence=confidence,
                        notes="Generated by matching rule task/family scope to training_recipes.task_id/model_family.",
                    )


def add_performance_requirement_edges(G: nx.MultiDiGraph, dfs: DataFrames) -> None:
    """
    Generate edges from performance_requirements.csv.

    Generated edges:
    - PerformanceRequirement --for_task--> Task, using task_id
    - PerformanceRequirement --uses_metric--> EvaluationMetric, using primary_metric_id
    """
    requirements = dfs.get("performance_requirements", pd.DataFrame())
    if requirements.empty or "id" not in requirements.columns:
        return

    for _, req in requirements.iterrows():
        req_id = _clean(req.get("id"))
        task_id = _clean(req.get("task_id"))
        metric_id = _clean(req.get("primary_metric_id"))

        _add_edge_if_nodes_exist(
            G,
            req_id,
            task_id,
            "for_task",
            notes="Generated from performance_requirements.task_id.",
        )
        _add_edge_if_nodes_exist(
            G,
            req_id,
            metric_id,
            "uses_metric",
            notes="Generated from performance_requirements.primary_metric_id.",
        )


def add_cv_problem_edges(G: nx.MultiDiGraph, dfs: DataFrames) -> None:
    """
    Generate edges from cv_problems.csv.

    Generated edges:
    - CVProblem --has_task--> Task
    - CVProblem --has_domain--> Domain
    - CVProblem --has_hardware_profile--> HardwareProfile
    - CVProblem --has_performance_requirement--> PerformanceRequirement
    """
    problems = dfs.get("cv_problems", pd.DataFrame())
    if problems.empty or "id" not in problems.columns:
        return

    field_to_relation = {
        "task_id": "has_task",
        "domain_id": "has_domain",
        "hardware_profile_id": "has_hardware_profile",
        "performance_requirement_id": "has_performance_requirement",
    }

    for _, problem in problems.iterrows():
        problem_id = _clean(problem.get("id"))
        for field, relation in field_to_relation.items():
            target_id = _clean(problem.get(field))
            _add_edge_if_nodes_exist(
                G,
                problem_id,
                target_id,
                relation,
                notes=f"Generated from cv_problems.{field}.",
            )


def add_dataset_requirement_edges(G: nx.MultiDiGraph, dfs: DataFrames) -> None:
    """
    Generate edges from dataset_requirements.csv.

    Generated edges:
    - DatasetRequirement --for_task--> Task, using task_id
    - DatasetRequirement --supported_by_evidence--> EvidenceSource, using optional evidence_ids
    """
    requirements = dfs.get("dataset_requirements", pd.DataFrame())
    if requirements.empty or "id" not in requirements.columns:
        return

    for _, req in requirements.iterrows():
        req_id = _clean(req.get("id"))
        task_id = _clean(req.get("task_id"))
        _add_edge_if_nodes_exist(
            G,
            req_id,
            task_id,
            "for_task",
            notes="Generated from dataset_requirements.task_id.",
        )

        if "evidence_ids" in requirements.columns:
            for evidence_id in _split_pipe(req.get("evidence_ids")):
                _add_edge_if_nodes_exist(
                    G,
                    req_id,
                    evidence_id,
                    "supported_by_evidence",
                    notes="Generated from dataset_requirements.evidence_ids.",
                )


def add_generated_edges(G: nx.MultiDiGraph, dfs: DataFrames) -> nx.MultiDiGraph:
    """
    Add all generated edges to the graph.

    Call this after:
    1. Loading all nodes from entity CSVs.
    2. Loading all manual edges from edges.csv.
    """
    add_training_recipe_edges(G, dfs)
    add_model_benchmark_result_edges(G, dfs)
    add_evaluation_metric_edges(G, dfs)
    add_adjustment_rule_edges(G, dfs)
    add_performance_requirement_edges(G, dfs)
    add_cv_problem_edges(G, dfs)
    add_dataset_requirement_edges(G, dfs)
    return G
